
'use server';
/**
 * @fileOverview A Genkit flow that uses a tool to create promo codes in Firestore.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';
import { adminDb } from '@/firebase/admin';
import * as admin from 'firebase-admin';
import { generateAnnouncement, GenerateAnnouncementInput, GenerateAnnouncementOutput } from './generate-announcement-flow';


// Define the tool's input schema using Zod
const PromoCodeSchema = z.object({
  code: z.string().describe("The unique promo code string. Must be uppercase, e.g., 'WELCOME25'."),
  discountPercentage: z.number().describe('The percentage discount, e.g., 25 for 25%.'),
  isActive: z.boolean().describe('Whether the code is currently active.'),
  expiresAt: z.string().optional().describe('Optional expiration date for the code in ISO 8601 format.'),
});

// Define the tool that the AI can use to create promo codes
const createPromoCode = ai.defineTool(
  {
    name: 'createPromoCode',
    description: 'Creates a new promotional code in the database. Use this tool ONLY when the user explicitly asks to CREATE a promo code, discount, or coupon.',
    inputSchema: PromoCodeSchema,
    outputSchema: z.object({
      success: z.boolean(),
      code: z.string(),
    }),
  },
  async (input) => {
    try {
      const promoCodeData: any = {
        code: input.code.toUpperCase(),
        discountPercentage: input.discountPercentage,
        isActive: input.isActive,
        createdAt: admin.firestore.FieldValue.serverTimestamp(),
      };
      if (input.expiresAt) {
        promoCodeData.expiresAt = admin.firestore.Timestamp.fromDate(new Date(input.expiresAt));
      }

      await adminDb.collection('promoCodes').add(promoCodeData);
      
      return { success: true, code: input.code };
    } catch (error) {
      console.error('Tool Error: Failed to create promo code', error);
      return { success: false, code: input.code };
    }
  }
);

// Define the tool for generating announcements
const generateAnnouncementTool = ai.defineTool(
    {
        name: 'generateAnnouncement',
        description: "Generates or improves a marketing announcement. Use this tool ONLY when the user's prompt is about WRITING an announcement, marketing message, or any other text content.",
        inputSchema: GenerateAnnouncementInput,
        outputSchema: GenerateAnnouncementOutput,
    },
    async (input) => {
        // This tool simply calls the existing flow function
        return await generateAnnouncement(input);
    }
);


// Define the input and output schemas for the main flow
const GeneratePromoCodeInputSchema = z.object({
  prompt: z.string().describe("The user's marketing request, e.g., 'Create a 20% discount for Easter' or 'Write an announcement for a new course'"),
});
export type GeneratePromoCodeInput = z.infer<typeof GeneratePromoCodeInputSchema>;

const GeneratePromoCodeOutputSchema = z.object({
  response: z.string().describe("A confirmation or generated message back to the user, in French."),
});
export type GeneratePromoCodeOutput = z.infer<typeof GeneratePromoCodeOutputSchema>;


// Define the prompt that uses the tool
const generatePromoCodePrompt = ai.definePrompt({
    name: 'generatePromoCodePrompt',
    input: { schema: GeneratePromoCodeInputSchema },
    output: { schema: GeneratePromoCodeOutputSchema },
    tools: [createPromoCode, generateAnnouncementTool],
    prompt: `You are Mathias, an AI marketing assistant for FormaAfrique.
    Your task is to help an administrator with marketing tasks.
    - First, determine the user's primary intent from their prompt. Is the user asking to CREATE a promo code, or are they asking to WRITE an announcement/message?

    - If the user's prompt is about CREATING a promotional code, discount, or coupon:
      - Analyze the user's prompt to determine the code name, discount percentage, and any expiration details.
      - If the user is vague, make reasonable assumptions (e.g., a 'welcome' code is active indefinitely, a holiday code might expire after the holiday).
      - You MUST use the 'createPromoCode' tool to save the new code to the database.
      - After calling the tool, respond to the user in French to confirm what you have done.
      - If the tool call is successful, say something like: "C'est fait ! Le code promo [CODE] offrant [XX]% de réduction a été créé et activé."
      - If the tool call fails, say: "Je suis désolé, je n'ai pas pu créer le code promo pour une raison technique."

    - If the user's prompt is about WRITING an announcement, marketing message, or any other text content:
      - You MUST call the 'generateAnnouncement' tool with the user's prompt as the 'topic'.
      - The tool will return the generated text. Your final response should ONLY be the announcement text generated by the tool.

    User's request: {{{prompt}}}
    `,
});


// Define the main flow that orchestrates the process
export const generatePromoCode = ai.defineFlow(
    {
        name: 'generatePromoCodeFlow',
        inputSchema: GeneratePromoCodeInputSchema,
        outputSchema: GeneratePromoCodeOutputSchema,
    },
    async (input) => {
        const { output } = await generatePromoCodePrompt(input);
        return output!;
    }
);
