
export interface Country {
  code: string;
  name: string;
  emoji: string;
  prefix: string;
}

export const africanCountries: Country[] = [
  { code: 'DZ', name: 'Algérie', emoji: '🇩🇿', prefix: '213' },
  { code: 'AO', name: 'Angola', emoji: '🇦🇴', prefix: '244' },
  { code: 'BJ', name: 'Bénin', emoji: '🇧🇯', prefix: '229' },
  { code: 'BW', name: 'Botswana', emoji: '🇧🇼', prefix: '267' },
  { code: 'BF', name: 'Burkina Faso', emoji: '🇧🇫', prefix: '226' },
  { code: 'BI', name: 'Burundi', emoji: '🇧🇮', prefix: '257' },
  { code: 'CV', name: 'Cabo Verde', emoji: '🇨🇻', prefix: '238' },
  { code: 'CM', name: 'Cameroun', emoji: '🇨🇲', prefix: '237' },
  { code: 'CF', name: 'République centrafricaine', emoji: '🇨🇫', prefix: '236' },
  { code: 'TD', name: 'Tchad', emoji: '🇹🇩', prefix: '235' },
  { code: 'KM', name: 'Comores', emoji: '🇰🇲', prefix: '269' },
  { code: 'CG', name: 'Congo', emoji: '🇨🇬', prefix: '242' },
  { code: 'CD', name: 'RD Congo', emoji: '🇨🇩', prefix: '243' },
  { code: 'CI', name: 'Côte d\'Ivoire', emoji: '🇨🇮', prefix: '225' },
  { code: 'DJ', name: 'Djibouti', emoji: '🇩🇯', prefix: '253' },
  { code: 'EG', name: 'Égypte', emoji: '🇪🇬', prefix: '20' },
  { code: 'GQ', name: 'Guinée équatoriale', emoji: '🇬🇶', prefix: '240' },
  { code: 'ER', name: 'Érythrée', emoji: '🇪🇷', prefix: '291' },
  { code: 'SZ', name: 'Eswatini', emoji: '🇸🇿', prefix: '268' },
  { code: 'ET', name: 'Éthiopie', emoji: '🇪🇹', prefix: '251' },
  { code: 'GA', name: 'Gabon', emoji: '🇬🇦', prefix: '241' },
  { code: 'GM', name: 'Gambie', emoji: '🇬🇲', prefix: '220' },
  { code: 'GH', name: 'Ghana', emoji: '🇬🇭', prefix: '233' },
  { code: 'GN', name: 'Guinée', emoji: '🇬🇳', prefix: '224' },
  { code: 'GW', name: 'Guinée-Bissau', emoji: '🇬🇼', prefix: '245' },
  { code: 'KE', name: 'Kenya', emoji: '🇰🇪', prefix: '254' },
  { code: 'LS', name: 'Lesotho', emoji: '🇱🇸', prefix: '266' },
  { code: 'LR', name: 'Libéria', emoji: '🇱🇷', prefix: '231' },
  { code: 'LY', name: 'Libye', emoji: '🇱🇾', prefix: '218' },
  { code: 'MG', name: 'Madagascar', emoji: '🇲🇬', prefix: '261' },
  { code: 'MW', name: 'Malawi', emoji: '🇲🇼', prefix: '265' },
  { code: 'ML', name: 'Mali', emoji: '🇲🇱', prefix: '223' },
  { code: 'MR', name: 'Mauritanie', emoji: '🇲🇷', prefix: '222' },
  { code: 'MU', name: 'Maurice', emoji: '🇲🇺', prefix: '230' },
  { code: 'MA', name: 'Maroc', emoji: '🇲🇦', prefix: '212' },
  { code: 'MZ', name: 'Mozambique', emoji: '🇲🇿', prefix: '258' },
  { code: 'NA', name: 'Namibie', emoji: '🇳🇦', prefix: '264' },
  { code: 'NE', name: 'Niger', emoji: '🇳🇪', prefix: '227' },
  { code: 'NG', name: 'Nigéria', emoji: '🇳🇬', prefix: '234' },
  { code: 'RW', name: 'Rwanda', emoji: '🇷🇼', prefix: '250' },
  { code: 'ST', name: 'Sao Tomé-et-Principe', emoji: '🇸🇹', prefix: '239' },
  { code: 'SN', name: 'Sénégal', emoji: '🇸🇳', prefix: '221' },
  { code: 'SC', name: 'Seychelles', emoji: '🇸🇨', prefix: '248' },
  { code: 'SL', name: 'Sierra Leone', emoji: '🇸🇱', prefix: '232' },
  { code: 'SO', name: 'Somalie', emoji: '🇸🇴', prefix: '252' },
  { code: 'ZA', name: 'Afrique du Sud', emoji: '🇿🇦', prefix: '27' },
  { code: 'SS', name: 'Soudan du Sud', emoji: '🇸🇸', prefix: '211' },
  { code: 'SD', name: 'Soudan', emoji: '🇸🇩', prefix: '249' },
  { code: 'TZ', name: 'Tanzanie', emoji: '🇹🇿', prefix: '255' },
  { code: 'TG', name: 'Togo', emoji: '🇹🇬', prefix: '228' },
  { code: 'TN', name: 'Tunisie', emoji: '🇹🇳', prefix: '216' },
  { code: 'UG', name: 'Ouganda', emoji: '🇺🇬', prefix: '256' },
  { code: 'ZM', name: 'Zambie', emoji: '🇿🇲', prefix: '260' },
  { code: 'ZW', name: 'Zimbabwe', emoji: '🇿🇼', prefix: '263' },
].sort((a, b) => a.name.localeCompare(b.name));
