import type { Course, User, Testimonial, Category } from './types';

const instructors = {
  yannick: { name: 'Yannick Noah', title: 'Ingénieur Full-Stack & IA', avatarId: 'instructor-yann' },
  aisha: { name: 'Aisha Keita', title: 'Stratège en Marketing & Data Scientist', avatarId: 'instructor-aisha' },
  david: { name: 'David Okoro', title: 'Serial Entrepreneur & Coach Agile', avatarId: 'instructor-david' },
};

export const courses: Course[] = [
  // Entrepreneuriat & Commerce
  {
    id: 'creation-entreprise',
    title: 'Les étapes clés de la création d’entreprise',
    category: 'Entrepreneuriat & Commerce',
    shortDescription: 'De l’idée à l’immatriculation, maîtrisez chaque étape pour lancer votre projet avec succès.',
    longDescription: 'Ce cours complet vous guide pas à pas dans le processus de création d’entreprise. Vous apprendrez à valider votre idée, à choisir votre statut juridique, et à accomplir toutes les démarches administratives.',
    instructor: instructors.david,
    imageId: 'course-entrepreneurship',
    enrollmentCount: 2345,
    duration: '6 semaines',
    level: 'Débutant',
    price: 15,
    dateAdded: '2024-07-20T10:00:00Z',
    whatYouWillLearn: ['Valider son idée', 'Choisir son statut juridique', 'Immatriculer son entreprise'],
    modules: [{ id: 'm1', title: 'De l\'idée au projet', duration: '25:00', videoUrl: '#', content: 'Comment transformer une intuition en un concept solide.' }],
  },
  {
    id: 'business-plan',
    title: 'Rédiger un Business Plan convaincant',
    category: 'Entrepreneuriat & Commerce',
    shortDescription: 'Apprenez à structurer un business plan qui séduira les investisseurs et guidera votre croissance.',
    longDescription: 'Un business plan solide est la feuille de route de votre succès. Ce cours vous apprend à définir votre marché, à projeter vos finances et à présenter votre vision de manière professionnelle.',
    instructor: instructors.david,
    imageId: 'course-entrepreneurship',
    enrollmentCount: 1890,
    duration: '4 semaines',
    level: 'Intermédiaire',
    price: 20,
    dateAdded: '2024-07-18T10:00:00Z',
    whatYouWillLearn: ['Analyse de marché', 'Prévisions financières', 'Stratégie marketing'],
    modules: [{ id: 'm1', title: 'Structure du Business Plan', duration: '20:00', videoUrl: '#', content: 'Les sections indispensables d\'un document professionnel.' }],
  },
  {
    id: 'e-commerce',
    title: 'Lancer sa boutique E-commerce en Afrique',
    category: 'Entrepreneuriat & Commerce',
    shortDescription: 'Vendez vos produits en ligne grâce à une boutique performante et adaptée au contexte africain.',
    longDescription: 'Ce cours pratique couvre tout ce dont vous avez besoin pour lancer votre site e-commerce : choix de la plateforme, solutions de paiement locales, logistique et marketing digital.',
    instructor: instructors.aisha,
    imageId: 'course-marketing',
    enrollmentCount: 3120,
    duration: '8 semaines',
    level: 'Intermédiaire',
    price: 30,
    dateAdded: '2024-07-15T10:00:00Z',
    whatYouWillLearn: ['Choisir sa plateforme', 'Intégrer les paiements mobiles', 'Gérer la logistique'],
    modules: [{ id: 'm1', title: 'Choisir sa solution e-commerce', duration: '30:00', videoUrl: '#', content: 'Shopify, WooCommerce ou solutions locales : que choisir ?' }],
  },
  // Compétences numériques
  {
    id: 'marketing-digital',
    title: 'Marketing Digital pour les TPE/PME',
    category: 'Compétences numériques',
    shortDescription: 'Attirez plus de clients grâce aux réseaux sociaux, au SEO et à la publicité en ligne.',
    longDescription: 'Ce cours vous donne les clés pour construire une stratégie de marketing digital efficace avec un budget maîtrisé. Idéal pour les petites et moyennes entreprises.',
    instructor: instructors.aisha,
    imageId: 'course-marketing',
    enrollmentCount: 4501,
    duration: '10 semaines',
    level: 'Débutant',
    price: 25,
    dateAdded: '2024-07-12T10:00:00Z',
    whatYouWillLearn: ['Stratégie social media', 'Bases du SEO', 'Publicité Facebook/Instagram'],
    modules: [{ id: 'm1', title: 'Définir sa stratégie digitale', duration: '18:00', videoUrl: '#', content: 'Comment fixer des objectifs clairs et mesurables.' }],
  },
  {
    id: 'developpement-web',
    title: 'Développement Web & Mobile pour débutants',
    category: 'Compétences numériques',
    shortDescription: 'Apprenez à créer vos propres sites web et applications mobiles de A à Z.',
    longDescription: 'Ce cours est une introduction complète au développement. Vous apprendrez les bases du HTML, CSS, JavaScript, puis vous vous initierez au framework React pour construire des projets concrets.',
    instructor: instructors.yannick,
    imageId: 'course-dev-web',
    enrollmentCount: 3800,
    duration: '12 semaines',
    level: 'Débutant',
    price: 40,
    dateAdded: '2024-07-10T10:00:00Z',
    whatYouWillLearn: ['HTML & CSS', 'JavaScript', 'Introduction à React'],
    modules: [{ id: 'm1', title: 'Les fondations du web', duration: '35:00', videoUrl: '#', content: 'Comprendre le fonctionnement d\'un site web.' }],
  },
  // Agriculture & Agro-industrie
  {
    id: 'agriculture-intelligente',
    title: 'Agriculture Intelligente face au changement climatique',
    category: 'Agriculture & Agro-industrie',
    shortDescription: 'Optimisez vos rendements et gérez mieux les ressources grâce aux nouvelles technologies.',
    longDescription: 'Découvrez comment l’agriculture de précision, les drones et les capteurs peuvent transformer votre exploitation pour la rendre plus résiliente et productive.',
    instructor: instructors.david,
    imageId: 'course-data-science',
    enrollmentCount: 980,
    duration: '8 semaines',
    level: 'Intermédiaire',
    price: 0,
    dateAdded: '2024-07-08T10:00:00Z',
    whatYouWillLearn: ['Agriculture de précision', 'Gestion de l\'eau', 'Utilisation de drones'],
    modules: [{ id: 'm1', title: 'Introduction à l\'AgriTech', duration: '22:00', videoUrl: '#', content: 'Les nouvelles technologies au service de l\'agriculteur.' }],
  },
  // Métiers manuels & Artisanat
  {
    id: 'couture-teinture',
    title: 'Techniques de Couture et Teinture Africaine',
    category: 'Métiers manuels & Artisanat',
    shortDescription: 'Apprenez les bases de la couture et les secrets des techniques de teinture traditionnelles.',
    longDescription: 'Ce cours vous initie à la couture à la machine et à la main, ainsi qu\'aux méthodes de teinture comme le bogolan ou l\'indigo. Créez vos propres pièces uniques.',
    instructor: instructors.aisha,
    imageId: 'course-project-management',
    enrollmentCount: 1540,
    duration: '10 semaines',
    level: 'Débutant',
    price: 10,
    dateAdded: '2024-07-05T10:00:00Z',
    whatYouWillLearn: ['Prise en main machine à coudre', 'Technique du Bogolan', 'Création d\'un patron simple'],
    modules: [{ id: 'm1', title: 'Le matériel de base', duration: '15:00', videoUrl: '#', content: 'Tout ce qu\'il vous faut pour démarrer en couture.' }],
  },
   // Éducation & Renforcement des capacités
  {
    id: 'tutoriels-scolaires',
    title: 'Tutoriels Scolaires - Niveau Lycée',
    category: 'Éducation & Renforcement des capacités',
    shortDescription: 'Soutien scolaire en mathématiques, physique-chimie et français pour réussir son baccalauréat.',
    longDescription: 'Ce programme de soutien scolaire propose des vidéos explicatives, des exercices corrigés et des fiches de révision pour les matières clés du lycée.',
    instructor: instructors.yannick,
    imageId: 'course-ai-ml',
    enrollmentCount: 5600,
    duration: 'À la demande',
    level: 'Débutant',
    price: 5,
    dateAdded: '2024-07-01T10:00:00Z',
    whatYouWillLearn: ['Résoudre des équations', 'Analyser un texte littéraire', 'Comprendre la stoechiométrie'],
    modules: [{ id: 'm1', title: 'Les fonctions du second degré', duration: '12:00', videoUrl: '#', content: 'Tout sur les paraboles.' }],
  },
  // Santé & Bien-être
  {
    id: 'hygiene-prevention',
    title: 'Hygiène et Prévention des maladies courantes',
    category: 'Santé & Bien-être',
    shortDescription: 'Adoptez les bons gestes pour vous protéger et protéger votre communauté des maladies infectieuses.',
    longDescription: 'Ce cours de santé publique aborde les gestes d\'hygiène de base, la prévention du paludisme, des maladies diarrhéiques et des infections respiratoires.',
    instructor: instructors.aisha,
    imageId: 'course-dev-web',
    enrollmentCount: 8900,
    duration: '4 semaines',
    level: 'Débutant',
    price: 0,
    dateAdded: '2024-06-28T10:00:00Z',
    whatYouWillLearn: ['Lavage des mains efficace', 'Prévention du paludisme', 'Salubrité de l\'eau'],
    modules: [{ id: 'm1', title: 'Les gestes qui sauvent', duration: '10:00', videoUrl: '#', content: 'L\'importance de l\'hygiène au quotidien.' }],
  },
  // Langues & Communication
  {
    id: 'anglais-debutant',
    title: 'Anglais pour Débutants',
    category: 'Langues & Communication',
    shortDescription: 'Apprenez les bases de l\'anglais pour voyager, travailler et communiquer avec le monde.',
    longDescription: 'Ce cours pour grands débutants vous apprendra les phrases essentielles, la grammaire de base et le vocabulaire indispensable pour tenir une conversation simple en anglais.',
    instructor: instructors.yannick,
    imageId: 'course-marketing',
    enrollmentCount: 10500,
    duration: '12 semaines',
    level: 'Débutant',
    price: 10,
    dateAdded: '2024-06-25T10:00:00Z',
    whatYouWillLearn: ['Se présenter', 'Commander au restaurant', 'Demander son chemin'],
    modules: [{ id: 'm1', title: 'Greetings and Introductions', duration: '8:00', videoUrl: '#', content: 'Les salutations et les présentations.' }],
  },
  // Finances & Inclusion économique
  {
    id: 'gestion-mobile-money',
    title: 'Maîtriser le Mobile Money',
    category: 'Finances & Inclusion économique',
    shortDescription: 'Utilisez votre téléphone pour gérer votre argent, payer vos factures et développer votre activité.',
    longDescription: 'Découvrez toutes les fonctionnalités offertes par les services de Mobile Money en Afrique. Apprenez à sécuriser votre compte, à effectuer des transferts, à payer des commerçants et à accéder à des services de micro-crédit et d\'épargne.',
    instructor: instructors.david,
    imageId: 'course-entrepreneurship',
    enrollmentCount: 12500,
    duration: '3 semaines',
    level: 'Débutant',
    price: 0,
    dateAdded: '2024-06-20T10:00:00Z',
    whatYouWillLearn: ['Sécuriser son compte', 'Paiements et transferts', 'Services d\'épargne'],
    modules: [{ id: 'm1', title: 'Les bases du Mobile Money', duration: '15:00', videoUrl: '#', content: 'Comment créer et sécuriser son portefeuille électronique.' }],
  },
];


export const users: User[] = [
  {
    id: 'user-1',
    name: 'Jean Dupont',
    email: 'jean.dupont@example.com',
    avatarId: 'user-avatar',
    enrolledCourses: ['developpement-web', 'business-plan']
  }
];

export const testimonials: Testimonial[] = [
  {
    id: 't1',
    name: 'Fatima Diallo',
    course: 'Développement Web & Mobile',
    quote: 'Cette formation a complètement changé ma carrière. Les explications sont claires et les projets pratiques m\'ont donné la confiance nécessaire pour postuler à des offres d\'emploi.',
    imageId: 'testimonial-fatima',
  },
  {
    id: 't2',
    name: 'Samuel Adebayo',
    course: 'Création d’entreprise',
    quote: 'Indispensable pour quiconque veut lancer son business en Afrique. Le cours est très concret et adapté à nos réalités. J\'ai pu lancer ma startup grâce aux conseils reçus.',
    imageId: 'testimonial-samuel',
  },
  {
    id: 't3',
    name: 'Chloé Dubois',
    course: 'Marketing Digital',
    quote: 'J\'avais des difficultés à trouver mes premiers clients. Après ce cours, j\'ai une stratégie claire et mes ventes ont décollé. Un grand merci à l\'équipe de FormaAfrique !',
    imageId: 'testimonial-chloe',
  }
];
